export enum blockNames {
  CallHeroImage = 'CallHeroImage',
  CallHeroText = 'CallHeroText',
  TwoColumnsUnit = 'TwoColumnsUnit',
  VideoHero = 'VideoHeroUnit',
  BlogListUnit= 'BlogListUnit',
  TeamListUnit = 'TeamListUnit',
  ProgramListUnit = 'ProgramListUnit',
  GameListUnit = 'GameListUnit',
  SmallHeroUnit = 'SmallHeroUnit',
  IntroUnit = 'IntroUnit',
  SpacerUnit = 'SpacerUnit',
  ProgramHeroUnit = 'ProgramHeroUnit',
  PricesSectionUnit = 'PricesSectionUnit',
  Promo1HeroUnit = 'Promo1HeroUnit',
  Promo2HeroUnit = 'Promo2HeroUnit',
  Column = 'VRBColumn',
  Columns = 'VRBColumns',

  Button = 'VRBButton',
  Text = 'VRBText',
  Title = 'VRBTitle',
  RichText = 'VRBRichText',
  Image = 'VRBImage',
  Label = 'VRBLabel',
  Customer = 'VRBCustomer',
  Customers = 'VRBCustomers',
  TeamCard = 'VRBTeamCard',
}